In [3]:
#!pip install --upgrade tensorflow
import tensorflow as tf
tf.__version__

'2.1.0'

In [4]:
import tensorflow as tf
from  tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils

Using TensorFlow backend.


In [0]:
#Array display should not be truncated
np.set_printoptions(threshold=np.inf)
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)
#np.set_printoptions(suppress=True,formatter={'float_kind':'{:0.2f}'.format}) 

In [0]:
iris = datasets.load_iris()
X = iris.data[:, :4]  # we take the first four features.
y = iris.target

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
X.shape

(150, 4)

In [8]:
y.shape

(150,)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y)
encoded_y = encoder.transform(y)
# convert integers to dummy variables (i.e. one hot encoded)
y_encoded = np_utils.to_categorical(encoded_y)

In [11]:
y_encoded

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y_encoded,test_size = 0.1)

In [0]:
model = Sequential()
#model.add(Dense(units=16, activation='relu',input_shape=(135,2)))
model.add(Dense(units=16, activation='relu',input_dim=4))
model.add(Dense(units=12, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

In [14]:
X_train.shape

(135, 4)

In [15]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 12)                204       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 39        
Total params: 323
Trainable params: 323
Non-trainable params: 0
_________________________________________________________________


In [16]:
history = model.fit(X_train, y_train, epochs=100, batch_size=5)

Train on 135 samples
Epoch 1/100
135/135 [==============================] - 0s 3ms/sample - loss: 1.5457 - accuracy: 0.3333
Epoch 2/100
135/135 [==============================] - 0s 383us/sample - loss: 1.0684 - accuracy: 0.3630
Epoch 3/100
135/135 [==============================] - 0s 370us/sample - loss: 0.9541 - accuracy: 0.4593
Epoch 4/100
135/135 [==============================] - 0s 369us/sample - loss: 0.8765 - accuracy: 0.5630
Epoch 5/100
135/135 [==============================] - 0s 352us/sample - loss: 0.8068 - accuracy: 0.8963
Epoch 6/100
135/135 [==============================] - 0s 356us/sample - loss: 0.7395 - accuracy: 0.7630
Epoch 7/100
135/135 [==============================] - 0s 371us/sample - loss: 0.6749 - accuracy: 0.9111
Epoch 8/100
135/135 [==============================] - 0s 383us/sample - loss: 0.6088 - accuracy: 0.8815
Epoch 9/100
135/135 [==============================] - 0s 391us/sample - loss: 0.5524 - accuracy: 0.8593
Epoch 10/100
135/135 [==============

In [17]:
_,accuracy = model.evaluate(X_test,y_test)

15/15 [==============================] - 0s 7ms/sample - loss: 0.0153 - accuracy: 1.0000


In [19]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

array([[1., 0., 0.]], dtype=float32)